# Generated by Django 4.2.19 on 2025-04-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_highlight_replied_to_savedfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfolder',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_posts', to='main.postsave'),
        ),
        migrations.DeleteModel(
            name='SavedPost',
        ),
    ]
