# Generated by Django 4.2.19 on 2025-04-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_savedfolder_saved_posts_delete_savedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfolder',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
